# Generated by Django 5.2.5 on 2025-08-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_transaction_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='accounting.balancegroup'),
        ),
    ]
