# Generated by Django 5.2.5 on 2025-08-19 04:10

import accounting.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_transaction_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['number'], 'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='balancearticle',
            options={'ordering': ['name'], 'verbose_name': 'Статья баланса', 'verbose_name_plural': 'Статьи баланса'},
        ),
        migrations.AlterModelOptions(
            name='balancegroup',
            options={'ordering': ['article__name', 'name'], 'verbose_name': 'Балансовая группа', 'verbose_name_plural': 'Балансовые группы'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_annulled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Балансы уже изменены'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='accounting.transaction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.balancegroup'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default=accounting.models.Account._generate_account_number, help_text='Уникальный 10‑значный номер счёта', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('A', 'Актив'), ('P', 'Пассив'), ('AP', 'Активно‑пассивный')], max_length=2),
        ),
        migrations.AlterField(
            model_name='balancearticle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='balancegroup',
            unique_together={('article', 'name')},
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_positive'),
        ),
    ]
